### ISSUE TITLE
Q: Is the Start2.bin only for Start menu ? What about taskbar ?

### ISSUE THREAD

**Issue by Boss-man** [mtniehaus/AutopilotBranding#12]
Hi

As the title says I tried adding new shortcuts to the taskbar, and then copy the Start2.bin file from my users folder.
But it didn't apply on the new machine.

Are there more to it when it comes to the taskbar shortcuts ?

**Comment by Boss-man** [comment]
I used to use that, but somehow it stopped working and reporting the XML file as invalid.

Its applied thru and Intune package so the xml file has not changed for a long time.

When trying to export a new one, its now being exported as a json file.

Will look at it again tomorrow.

**Comment by Boss-man** [comment]
Looked at it some more and found this thread on reddit: https://www.reddit.com/r/MDT/comments/1cljzib/comment/l2y7sx3/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Here it seems that a newer build of W11 broke the import-startlayout command.

I'll now try this solution instead, unless there is a better way: https://www.everything365.online/2023/07/21/deploy-a-customized-windows-11-taskbar-that-allows-users-to-change-the-pinned-apps/

**Comment by kcyberman17** [comment]
Here is what I did for the Taskbar instead of what is in the script.

`Copy-Item "$($installFolder)Layout.xml" "C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\TaskbarLayoutModification.xml" -Force`

**Comment by mtniehaus** [comment]
Changes have been merged now to handle both:  Copying Start2.bin for the Start layout, and the layout.xml for the task bar layout.  (Windows 11 implemented a new mechanism for Start, but still uses the same setup for the task bar.)
