### ISSUE TITLE
Multiple issues on 24H2

### ISSUE THREAD

**Issue by SFMextrico** [mtniehaus/AutopilotBranding#13]
Heyo

These are my experiences with AutopilotBranding on 24H2 so far:

- Windows Background is defaulting to Windows Spotlight, overwriting the customized background, even if Windows Spotlight get's disabled earlier in the script.
- Setting location registry keys terminates the script due to  "path not existing" even though they do.
- General Customization doesn't work off the bat as it does in earlier build, it needs the device to be rebooted multiple times, before start menu is configured correctly.
- Toolbar customizations such as icons seems to be working 50% of the time, changing the search bar to icon does not work
- Context menu registry "hack" does not work, at all. Have had to create a platform script for this
- Downloading and installing onedrive gets stuck, and makes autopilot deployment timeout, needed to add a timeout for the installation or remove it entirely.

I'll add if I find other errors

**Comment by kcyberman17** [comment]
I found a different way of doing the toolbar that seems to be working, at least in my testing. I have not deployed this to production yet as I am still working through issues with the Windows Background being overwritten by Windows Spotlight. I have not found a workaround for that and it is driving me nuts.

Here is my workaround for the Toolbar.
`Copy-Item` "$($installFolder)Layout.xml" C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\TaskbarLayoutModification.xml" -Force`

**Comment by SFMextrico** [comment]
I got the toolbar customization working by simply creating a settings catalog configuration that I deploy to the device group :)
Will try your way!

I've got the Windows Background working by adding this part to my script before setting the theme:

`Log "Disabling Windows Spotlight for Desktop"
reg.exe add "HKLM\TempUser\Software\Policies\Microsoft\Windows\CloudContent" /v DisableSpotlightCollectionOnDesktop /t REG_DWORD /d 1 /f | Out-Host`

**Comment by harrybamber** [comment]
@SFMextrico that worked a treat for Windows Background issue, thank you!

**Comment by mtniehaus** [comment]
Merged changes.
