### ISSUE TITLE
OEM information and OEM used to work on windows 10 versions 2004 and older. It doesn't seem to work on 20H2. does it mean Microsoft removed the OEM feature ? i am not even able to do it manually. 

### ISSUE THREAD

**Issue by HeeroEliana** [mtniehaus/AutopilotBranding#6]

**Comment by PiKappZ746** [comment]
This still works.  I just checked 21H1 and Windows 11 PCs that I ran through autopilot last week.  I only use Manufacturer, Phone and Website.

**Comment by boivinx7** [comment]
Should still work but its in Settings
https://www.tenforums.com/tutorials/76570-customize-oem-support-information-windows-10-a.html

**Comment by mtniehaus** [comment]
I just checked on Windows 11 23H2 and it's working fine.  They have made the information a little less visible in Settings, it's under System > About in the "Support" section.

![image](https://github.com/mtniehaus/AutopilotBranding/assets/16982296/543a0ec6-b64d-42a2-a6ad-cc404d413c26)
