### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by nitram-rem** [mtniehaus/AutopilotBranding#7]
HI Michael,

i have some issues with Autopilot branding. I used your script since a while but i have now the new challenge to setup a device with Dutch and English as a second language. Because there are no Language Cab's anymore i do not really know how. I tried to install the Language Experience Pack's out of the MS store but the question is than still how can i control the Language settings (Display, Regional and so on) at the client. Is there a "new" way to distribute and control the language on the client?

**Comment by boivinx7** [comment]
.iso from MSDN still have the CAB's for most recent Windows 10 versions
it just stops at 2004 but its compatible 2004 and UP

"Versions 2004 and newer:
• The Language Packs released with Windows 10, version 2004 are also compatible with version 20H2 and newer media.
• For adding languages to images using LXPs (Local Experience Packs), please see this [site](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue) to determine which LXP ISO to use."

**Comment by mtniehaus** [comment]
LXPs seem to have been a failed experiment -- with Windows 11, they went back to LP.CABs.  See https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-language-imaging-in-windows-11/ba-p/2758043.
