### ISSUE TITLE
Using *.deskthemepack instead *.theme files

### ISSUE THREAD

**Issue by RazielLycas** [mtniehaus/AutopilotBranding#9]
Hi, thanks for your work.
I'm trying to cusotmize deploy during autopilot but our theme is a deskthemepack file instead a theme.
With that package theme isn't applied, I've tried adding an invoke command: 

$Windows10Theme = "C:\Windows\Resources\OEMThemes\RED.deskthemepack"
Invoke-Expression $Windows10Theme

but doesn't work during autopilot, works isntead with OS already started

**Comment by antiquatedIT** [comment]
Hi, I realize you posted this quite some time ago but thought I would reply in case others coming across this see it.  The .theme file (and background) is located within the .deskthemepack file.  You can extract it using something like 7zip or winrar and will get a resulting .theme file along with a background folder.  I haven't used this script yet, but judging from the folder structure, I think it will just get placed in the "AutopilotBranding" folder and then updated to your own .theme name and background name in the script.
